### ISSUE TITLE
[x11] SystemError: More keyword list entries (4) than format specifiers (3)

### ISSUE THREAD

**Issue by einarf** [moderngl/glcontext#3]
Looks like we left a stinker in the x11 backend.

```
$ python examples/basic_colors_and_texture.py 
2019-11-14 11:52:33,468 - moderngl_window - INFO - Attempting to load window class: moderngl_window.context.pyglet.Window
Traceback (most recent call last):
  File "examples/basic_colors_and_texture.py", line 126, in <module>
    ColorsAndTexture.run()
  File "/home/einarf/Documents/projects/moderngl/moderngl/examples/ported/_example.py", line 21, in run
    mglw.run_window_config(cls)
  File "/home/einarf/Documents/projects/moderngl/moderngl/.venv/lib/python3.7/site-packages/moderngl_window/__init__.py", line 185, in run_window_config
    cursor=show_cursor if show_cursor is not None else True,
  File "/home/einarf/Documents/projects/moderngl/moderngl/.venv/lib/python3.7/site-packages/moderngl_window/context/pyglet/window.py", line 71, in __init__
    self.init_mgl_context()
  File "/home/einarf/Documents/projects/moderngl/moderngl/.venv/lib/python3.7/site-packages/moderngl_window/context/base/window.py", line 137, in init_mgl_context
    self._ctx = moderngl.create_context(require=self.gl_version_code)
  File "/home/einarf/Documents/projects/moderngl/moderngl/moderngl/context.py", line 1236, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(None, standalone, require)
  File "/home/einarf/Documents/projects/moderngl/moderngl/.venv/lib/python3.7/site-packages/glcontext/__init__.py", line 25, in <lambda>
    return lambda glversion: x11.create_context(mode=mode, glversion=glversion)
SystemError: More keyword list entries (4) than format specifiers (3)
```

**Comment by einarf** [comment]
Fixed in 8aa350ac812d69fe08d620961059a04d77e7c8b7
